<a href="https://colab.research.google.com/github/alademk65/TTA_alademk65/blob/main/HLT_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/


In [ ]:
##TASK 1
dn = open("Numbers.txt", "w")
dn.write("3\n45")
dn.close()

! ls -1

dn1 = open("Numbers.txt","r")
dn2= dn1.read()
dn2


data11.txt
gdrive
Numbers.txt
sample_data
tta_file


'3\n45'

In [ ]:
##TASK 1


dn3= open("Numbers.txt", "a")
dn3.write("\n83\n21")
dn3.close()


In [ ]:
##TASK 1
dn4= open("Numbers.txt", "r")
dn5= dn4.read()
dn5

'3\n45\n83\n21'

In [ ]:
##TASK 1
dn5.replace("\n",",")

'3,45,83,21'

In [ ]:
my_file = open("data11.txt", "w")
for i in range(10):
  my_file.write(str(i))
  my_file.write("\n")
my_file.close() 

! ls -1

data11.txt
gdrive
Numbers.txt
sample_data
tta_file


In [ ]:
##Task2
myName = input("Hello! What is your name? ")

print("Well, " + myName + " What is your percentage mark to be graded?.")

mark = float(input("Enter your percentage mark:") )
def mark_grade (mark):
      if mark >= 70 and mark <= 100:
        return "Your grade : Distinction" 
      elif guess >= 60 and guess <= 69.5:
        return "Your grade : Merit"
      elif guess >= 40 and guess <= 59.5:
        return "Your grade : Pass"
      elif guess <40:
        return "Your grade : Fail"
      else:
        return "Enter only your mark"


mark_grade(78)

Hello! What is your name? mk
Well, mk What is your percentage mark to be graded?.
Enter your percentage mark:78


'Your grade : Distinction'

In [9]:
##task3

import numpy as np

a1= np.arange(1,10)
print("\n",a1)

b2 =np.ones((3,3),dtype=bool)
print("\n2",b2)

c3= np.arange(1,11)
print("\n",c3[c3 % 2 == 1])

d4= np.arange(1,11)
d4[d4 % 2 == 1]= -1
print("\n",d4)

e5=np.arange(1,5).reshape(2,2)
print("\n",e5)





 [1 2 3 4 5 6 7 8 9]

2 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

 [1 3 5 7 9]

 [-1  2 -1  4 -1  6 -1  8 -1 10]

 [[1 2]
 [3 4]]


In [11]:
##Task 3
import numpy as np
a = np.arange (1,5).reshape (2,2) 
b = np.arange (5,9).reshape (2,2) 

cv= np.vstack((a,b))
print("\n",cv)

s1= np.sum(cv,axis=0)
print("\n",s1)

r1= np.sum(cv,axis=1)
print("\n",r1)

s=np.sum(cv)
print("\n",s)

d = np.dot(a,b)
print("\n",d)

e= np.sum(d,axis=0)
print("\n",e)

f= np.sum(d,axis=1)
print("\n",f)

g=np.sum(a)
print("\n",g)

h=np.sum(b)
print("\n",h)


 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

 [16 20]

 [ 3  7 11 15]

 36

 [[19 22]
 [43 50]]

 [62 72]

 [41 93]

 10

 26
